name: Build and Publish Python Package on Any Push

on:
  push:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get short commit SHA
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update version in pyproject.toml
        run: |
          # Формат версии с хешем коммита, например 0.1.1+gabcdef1
          sed -i "s|^version = .*|version = \"0.1.1+g${COMMIT_SHA}\"|" pyproject.toml

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
